# https://travis-ci.org/#!/translate/terminator
language: python
python:
  - 2.5
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4.5
  # DJANGO_VERSION=1.5
# when we do finally support Django 1.5 - it requires Python 2.6.5, so exclude
# earlier versions (see https://docs.djangoproject.com/en/dev/faq/install/)
matrix:
  exclude:
    - python: 2.5
      env: DJANGO_VERSION=1.5
install:
  - pip install --use-mirrors Django==$DJANGO_VERSION
  - case `python -V 2>&1` in *2.5*) pip install -r requirements/py25.txt ;; esac
  - pip install -r requirements/build.txt --use-mirrors
  - python -V; pip freeze # print all installed versions for reference/posterity
script:
  - project/manage.py runserver &
  - TESTPID=$!
  - sleep 100
  - kill -2 $TESTPID
notifications:
  email:
    on_failure: always
    on_success: change
